-- Approved agents table used by the agents management listing.
CREATE TABLE IF NOT EXISTS `approved_agents` (
  `agent_id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `reference_code` varchar(50) NOT NULL,
  `client_number` varchar(30) DEFAULT NULL,
  `client_type` enum('individual','corporate','obligee') NOT NULL DEFAULT 'individual',
  `client_name` varchar(200) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `mobile_phone` varchar(20) DEFAULT NULL,
  `office_phone` varchar(20) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `verification_status` enum('draft','pending','verified','rejected') DEFAULT 'draft',
  `submitted_by` int(11) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `verified_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `last_transaction_date` date DEFAULT NULL,
  `activity_status` enum('active','inactive','deactivated') DEFAULT NULL,
  `activity_status_updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`agent_id`),
  UNIQUE KEY `uniq_approved_agents_client_id` (`client_id`),
  UNIQUE KEY `uniq_approved_agents_reference_code` (`reference_code`),
  KEY `idx_approved_agents_client_type` (`client_type`),
  KEY `idx_approved_agents_status` (`verification_status`),
  KEY `idx_approved_agents_submitted_by` (`submitted_by`),
  KEY `idx_approved_agents_verified_by` (`verified_by`),
  KEY `idx_approved_agents_last_transaction_date` (`last_transaction_date`),
  KEY `idx_approved_agents_activity_status` (`activity_status`),
  CONSTRAINT `approved_agents_ibfk_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON DELETE CASCADE,
  CONSTRAINT `approved_agents_ibfk_submitted_by` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL,
  CONSTRAINT `approved_agents_ibfk_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Backfill verified agents into the approved agents table.
INSERT INTO `approved_agents` (
  `client_id`,
  `reference_code`,
  `client_number`,
  `client_type`,
  `client_name`,
  `first_name`,
  `middle_name`,
  `last_name`,
  `mobile_phone`,
  `office_phone`,
  `email`,
  `verification_status`,
  `submitted_by`,
  `submitted_at`,
  `verified_by`,
  `created_at`,
  `last_transaction_date`,
  `activity_status`,
  `activity_status_updated_at`
)
SELECT
  a.`client_id`,
  a.`reference_code`,
  a.`client_number`,
  a.`client_type`,
  a.`client_name`,
  a.`first_name`,
  a.`middle_name`,
  a.`last_name`,
  a.`mobile_phone`,
  a.`office_phone`,
  a.`email`,
  a.`verification_status`,
  a.`submitted_by`,
  a.`submitted_at`,
  a.`verified_by`,
  a.`created_at`,
  a.`last_transaction_date`,
  a.`activity_status`,
  a.`activity_status_updated_at`
FROM `agents` a
WHERE a.`verification_status` = 'verified'
ON DUPLICATE KEY UPDATE
  `client_number` = VALUES(`client_number`),
  `client_type` = VALUES(`client_type`),
  `client_name` = VALUES(`client_name`),
  `first_name` = VALUES(`first_name`),
  `middle_name` = VALUES(`middle_name`),
  `last_name` = VALUES(`last_name`),
  `mobile_phone` = VALUES(`mobile_phone`),
  `office_phone` = VALUES(`office_phone`),
  `email` = VALUES(`email`),
  `verification_status` = VALUES(`verification_status`),
  `submitted_by` = VALUES(`submitted_by`),
  `submitted_at` = VALUES(`submitted_at`),
  `verified_by` = VALUES(`verified_by`),
  `last_transaction_date` = VALUES(`last_transaction_date`),
  `activity_status` = VALUES(`activity_status`),
  `activity_status_updated_at` = VALUES(`activity_status_updated_at`),
  `updated_at` = CURRENT_TIMESTAMP;