-- Create dedicated agents table for agent-form submissions and agents management listing.
CREATE TABLE IF NOT EXISTS `agents` (
  `agent_id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `reference_code` varchar(50) NOT NULL,
  `client_number` varchar(30) DEFAULT NULL,
  `client_type` enum('individual','corporate','obligee') NOT NULL DEFAULT 'individual',
  `client_name` varchar(200) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `mobile_phone` varchar(20) DEFAULT NULL,
  `office_phone` varchar(20) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `verification_status` enum('draft','pending','verified','rejected') DEFAULT 'draft',
  `submitted_by` int(11) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `verified_by` int(11) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`agent_id`),
  UNIQUE KEY `uniq_agents_client_id` (`client_id`),
  UNIQUE KEY `uniq_agents_reference_code` (`reference_code`),
  KEY `idx_agents_client_type` (`client_type`),
  KEY `idx_agents_status` (`verification_status`),
  KEY `idx_agents_submitted_by` (`submitted_by`),
  KEY `idx_agents_verified_by` (`verified_by`),
  CONSTRAINT `agents_ibfk_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON DELETE CASCADE,
  CONSTRAINT `agents_ibfk_submitted_by` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL,
  CONSTRAINT `agents_ibfk_verified_by` FOREIGN KEY (`verified_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Backfill current agent-classified clients.
INSERT INTO `agents` (
  `client_id`,
  `reference_code`,
  `client_number`,
  `client_type`,
  `client_name`,
  `first_name`,
  `middle_name`,
  `last_name`,
  `mobile_phone`,
  `office_phone`,
  `email`,
  `verification_status`,
  `submitted_by`,
  `submitted_at`,
  `verified_by`,
  `created_at`
)
SELECT
  c.`client_id`,
  c.`reference_code`,
  c.`client_number`,
  c.`client_type`,
  c.`client_name`,
  c.`first_name`,
  c.`middle_name`,
  c.`last_name`,
  c.`mobile_phone`,
  c.`office_phone`,
  c.`email`,
  c.`verification_status`,
  c.`submitted_by`,
  c.`submitted_at`,
  c.`verified_by`,
  c.`created_at`
FROM `clients` c
WHERE COALESCE(NULLIF(LOWER(TRIM(c.`client_classification`)), ''), 'client') = 'agent'
ON DUPLICATE KEY UPDATE
  `reference_code` = VALUES(`reference_code`),
  `client_number` = VALUES(`client_number`),
  `client_type` = VALUES(`client_type`),
  `client_name` = VALUES(`client_name`),
  `first_name` = VALUES(`first_name`),
  `middle_name` = VALUES(`middle_name`),
  `last_name` = VALUES(`last_name`),
  `mobile_phone` = VALUES(`mobile_phone`),
  `office_phone` = VALUES(`office_phone`),
  `email` = VALUES(`email`),
  `verification_status` = VALUES(`verification_status`),
  `submitted_by` = VALUES(`submitted_by`),
  `submitted_at` = VALUES(`submitted_at`),
  `verified_by` = VALUES(`verified_by`),
  `updated_at` = CURRENT_TIMESTAMP;