-- Head Office approval queue for incoming agent submissions.
CREATE TABLE IF NOT EXISTS `agent_approvals` (
  `approval_id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `reference_code` varchar(50) NOT NULL,
  `client_number` varchar(30) DEFAULT NULL,
  `client_classification` enum('agent') NOT NULL DEFAULT 'agent',
  `client_type` enum('individual','corporate','obligee') NOT NULL DEFAULT 'individual',
  `display_name` varchar(200) DEFAULT NULL,
  `client_name` varchar(200) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `middle_name` varchar(50) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `mobile_phone` varchar(20) DEFAULT NULL,
  `office_phone` varchar(20) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `submitted_by` int(11) DEFAULT NULL,
  `submitted_by_branch` varchar(80) DEFAULT NULL,
  `submitted_at` datetime DEFAULT NULL,
  `approval_status` enum('pending','approved','declined','resubmit') NOT NULL DEFAULT 'pending',
  `review_notes` text DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`approval_id`),
  UNIQUE KEY `uniq_agent_approvals_client_id` (`client_id`),
  UNIQUE KEY `uniq_agent_approvals_reference_code` (`reference_code`),
  KEY `idx_agent_approvals_status` (`approval_status`),
  KEY `idx_agent_approvals_classification` (`client_classification`),
  KEY `idx_agent_approvals_type` (`client_type`),
  KEY `idx_agent_approvals_submitted_by` (`submitted_by`),
  KEY `idx_agent_approvals_reviewed_by` (`reviewed_by`),
  CONSTRAINT `agent_approvals_ibfk_client` FOREIGN KEY (`client_id`) REFERENCES `clients` (`client_id`) ON DELETE CASCADE,
  CONSTRAINT `agent_approvals_ibfk_submitted_by` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL,
  CONSTRAINT `agent_approvals_ibfk_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Backfill existing agent approvals that are not yet approved.
INSERT INTO `agent_approvals` (
  `client_id`,
  `reference_code`,
  `client_number`,
  `client_classification`,
  `client_type`,
  `display_name`,
  `client_name`,
  `first_name`,
  `middle_name`,
  `last_name`,
  `contact_person`,
  `mobile_phone`,
  `office_phone`,
  `email`,
  `submitted_by`,
  `submitted_by_branch`,
  `submitted_at`,
  `approval_status`,
  `review_notes`,
  `reviewed_by`,
  `reviewed_at`,
  `approved_at`,
  `created_at`
)
SELECT
  ca.`client_id`,
  ca.`reference_code`,
  ca.`client_number`,
  'agent' AS `client_classification`,
  ca.`client_type`,
  COALESCE(
    NULLIF(TRIM(ca.`display_name`), ''),
    NULLIF(TRIM(ca.`client_name`), ''),
    NULLIF(TRIM(ca.`contact_person`), ''),
    NULLIF(TRIM(CONCAT(COALESCE(ca.`first_name`, ''), ' ', COALESCE(ca.`last_name`, ''))), ''),
    ca.`reference_code`
  ) AS `display_name`,
  ca.`client_name`,
  ca.`first_name`,
  ca.`middle_name`,
  ca.`last_name`,
  ca.`contact_person`,
  ca.`mobile_phone`,
  ca.`office_phone`,
  ca.`email`,
  ca.`submitted_by`,
  ca.`submitted_by_branch`,
  ca.`submitted_at`,
  ca.`approval_status`,
  ca.`review_notes`,
  ca.`reviewed_by`,
  ca.`reviewed_at`,
  ca.`approved_at`,
  ca.`created_at`
FROM `client_approvals` ca
WHERE COALESCE(NULLIF(LOWER(TRIM(ca.`client_classification`)), ''), 'client') = 'agent'
  AND ca.`approval_status` IN ('pending', 'declined', 'resubmit')
ON DUPLICATE KEY UPDATE
  `client_number` = VALUES(`client_number`),
  `client_type` = VALUES(`client_type`),
  `display_name` = VALUES(`display_name`),
  `client_name` = VALUES(`client_name`),
  `first_name` = VALUES(`first_name`),
  `middle_name` = VALUES(`middle_name`),
  `last_name` = VALUES(`last_name`),
  `contact_person` = VALUES(`contact_person`),
  `mobile_phone` = VALUES(`mobile_phone`),
  `office_phone` = VALUES(`office_phone`),
  `email` = VALUES(`email`),
  `submitted_by` = VALUES(`submitted_by`),
  `submitted_by_branch` = VALUES(`submitted_by_branch`),
  `submitted_at` = VALUES(`submitted_at`),
  `approval_status` = VALUES(`approval_status`),
  `review_notes` = VALUES(`review_notes`),
  `reviewed_by` = VALUES(`reviewed_by`),
  `reviewed_at` = VALUES(`reviewed_at`),
  `approved_at` = VALUES(`approved_at`),
  `updated_at` = CURRENT_TIMESTAMP;